[package]
name = "subdomain-redirector"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.9"
clap = { version = "4.6.5", features = ["derive", "env"] }
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["macros", "net", "rt-multi-thread", "sync"] }
toml = "1.1.4"
